/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#6cfad4',
        'surface-container': '#1c201f',
        'on-surface': '#e0e3e0',
        'outline-variant': '#3b4a45',
        'inverse-surface': '#e0e3e0',
        'on-primary-fixed-variant': '#005141',
        'surface-tint': '#32deb9',
        'surface-variant': '#323634',
        'on-primary': '#00382c',
        'on-secondary-fixed': '#002018',
        'tertiary-fixed-dim': '#c0c8c5',
        'tertiary': '#d0d9d5',
        'on-tertiary': '#2a3230',
        'tertiary-container': '#b4bdba',
        'surface-container-high': '#272b29',
        'primary-container': '#19d3ae',
        'on-secondary-container': '#004234',
        'on-tertiary-fixed-variant': '#404946',
        'surface-container-low': '#181c1b',
        'error': '#ffb4ab',
        'tertiary-fixed': '#dce4e1',
        'primary': '#4cf0c9',
        'on-error': '#690005',
        'inverse-on-surface': '#2d3130',
        'on-error-container': '#ffdad6',
        'primary-fixed-dim': '#32deb9',
        'surface-container-lowest': '#0b0f0e',
        'secondary': '#4addb9',
        'surface-bright': '#363a38',
        'on-surface-variant': '#bacac3',
        'surface': '#101413',
        'inverse-primary': '#006b57',
        'background': '#101413',
        'error-container': '#93000a',
        'outline': '#85948e',
        'surface-container-highest': '#323634',
        'on-background': '#e0e3e0',
        'surface-dim': '#101413',
        'on-secondary': '#00382c',
        'on-secondary-fixed-variant': '#005140',
        'primary-fixed': '#5bfbd4',
        'on-tertiary-fixed': '#151d1b',
        'on-primary-fixed': '#002019',
        'on-primary-container': '#005645',
        'secondary-container': '#00b896',
        'secondary-fixed-dim': '#4addb9',
        'on-tertiary-container': '#444d4a'
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      spacing: {
        gutter: '24px',
        'container-padding-mobile': '20px',
        'container-padding-desktop': '40px',
        unit: '8px',
        'section-gap': '80px',
      }
    },
  },
  plugins: [],
}